### ISSUE TITLE
abstract moveit_interface class to abstract planner_interface 

### ISSUE THREAD

**Issue by swhart115** [swhart115/nasa_robot_teleop#7]
right now NRT is explicitly dependent on MoveIt! to generate plans and set things up (it uses a lot of the MoveIt! setup wizard generated files; most importantly the SRDF file).  

While i think relying on these setup files is a good thing (it allows for the automatic discovery of poses, manipulator, joint, and end-effector groups, controller names, etc.), it might be beneficial to abstract the class/functions that do the path planning (and execution) into something more general.

That way if the user wanted a simple IK or min-jerk traj generator or whatever, they can use that instead of MoveIt!

A suggestion would be to keep the structure of the MoveIt! config package files, but allow planning and execution to be done by a non-MoveIt! trajectory generator.

**Comment by hambuchen** [comment]
Are you currently working on this? This is my next big thing I want to do - I need to use the planner for R2 now, since it does multiple manipulator motion, albeit w/o any collision avoidance. But I think this is the next major step for R2 on ISS ops.

**Comment by swhart115** [comment]
Yes, feature/abstracted_trajectory_solver is where i'm holding it.  It
is very messy right now because of all the Atlas hacks i had to make in
SC.  I will be cleaning it up today and this week.  The basic structure is
working, but i make no promises that there isnt some messy/broken stuff in
there if you tried to check it out and run it right now.  You can take a
look at PathPlanner.py as the general class, and then MoveItPathPlanner.py
and AtlasPathPlanner.py as the instances.  The latter actually, mostly just
calls new service calls and doesnt actually do hte planning itself.  With a
little bit of work that could probably be changed to
PathPlannerServiceInterface.py or something.

The most complicated thing i'm trying to get working with this change is
wrt the SRDF.  This format was developed for MoveIt! and is useful at some
level, but really should a) be more general then MoveIt! and b) have
more/diifferent stuff in it.  For the way they did Atlas (similar to WBC,
and correct for humanoids and more dynamic systems then PR2s or R2 upper
bodies), is that the concept of "groups" are kind of limiting (e.g. how do
we include the waist or leg joints when trying to reach out a hand?).

I'd say take a look, and if you ahve suggestions on what you would like to
see or not see here, let me know asap, cause i'm probably gonna make some
changes and run with it till the competition, but I would like to see it
merged into develop (i.e., working with R2), even if there are some messy
things around the edges that are some short-term decisions to help with
Atlas.

**Comment by hambuchen** [comment]
OK - I've said that this is going to take a while and put a May 29th milestone on it for integrating the R2 planner, so I'm not in any hurry here. I'll take a look at it this week but won't do any work on it until you've finished the SRDF stuff, or at least have it to a stable point. Currently I'm going to add the handrail detector into the perceptual registration stuff, so I'll probably be working that for a couple of weeks.

**Comment by swhart115** [comment]
develop currently has addressed this issue.  Existing planners include a moveit interface and an atlas interface.  I am going to change the later to a more general service-based interface, but the structure is in place.
