### ISSUE TITLE
figure out why path visualization meshs done respect alpha transparency settings 

### ISSUE THREAD

**Issue by swhart115** [swhart115/nasa_robot_teleop#8]
at some point, the path viz meshes started showing as solid, regardless of what the alpha was set to.  not sure if it was a ros change that made this happen, of if there was a change that made how i was setting this up not work anymore. wha?

**Comment by hambuchen** [comment]
This works for me. I set the alpha value low and am regularly seeing transparent plans. I can't reproduce your bug.

**Comment by swhart115** [comment]
they just released updates to RViz. They might have fixed this finally.
good.

**Comment by swhart115** [comment]
i',m still not seeing this. maybe its a graphics card issue?

**Comment by swhart115** [comment]
Not sure why this is user-dependent, but i'm changing to "wontfix" cause it is a purely aesthetic issue that i dont care to debug anymore.
